book_google_books_api:
    resource: "@BookGoogleBooksApiBundle/Resources/config/routing.yml"
    prefix:   /



#book_user:
 #   resource: "@BookUserBundle/Resources/config/routing.yml"
  #  prefix:   /

book_review:
    resource: "@BookReviewBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

book_api:
    type: rest
    resource: "@BookApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1