api_book:
    type: rest
    resource: Book\ApiBundle\Controller\BookController
    name_prefix: api_book_
    prefix: /

api_review:
    type: rest
    resource: Book\ApiBundle\Controller\ReviewController
    name_prefix: api_review_
    prefix: /

